name: GitHub sync test

on:
  workflow_dispatch:

permissions: read-all

jobs:
  gh-sync:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: set token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token
      - name: GitHub sync
        uses: docker://ghcr.io/uwu-tools/peribolos@sha256:d6a2677e516c2958eb0269f30dabc104ea88de5a27d59cd6374919cfa807c14f # latest
        with:
          github-token-path: ./token
          dump: relengfam
